### ISSUE TITLE
Fatal Error: Knp\Menu\MenuItem::setCurrentUri()

### ISSUE THREAD

**Issue by grantlovell** [Sylius/Sylius-Sandbox#61]
Attempting to view the administration dashboard, a fatal error is given:
Fatal error: Call to undefined method Knp\Menu\MenuItem::setCurrentUri() in /sylius-sandbox/src/Sylius/Sandbox/Bundle/CoreBundle/Menu/Builder.php on line 160

This is due to changes made to the master branch of the KnpMenuBundle see:
https://github.com/KnpLabs/KnpMenu/issues/63 for more details on the changes.

**Comment by grantlovell** [comment]
A work around is to comment out lines 160 & 198:
$menu->setCurrentUri($this->container->get('request')->getRequestUri());

in /sylius-sandbox/src/Sylius/Sandbox/Bundle/CoreBundle/Menu/Builder.php

This is not ideal, I will look into the proper way to set the current menu item.

**Comment by pjedrzejewski** [comment]
This should be fixed IIRC, are you using latest versions of sandbox and KnpMenu?

**Comment by grantlovell** [comment]
I see this was already dealt with in issue #57 and #58. I'm pretty sure I am using the latest of both Sylius-Sandbox and KnpMenu, I followed the directions in README.md for Sylius-Sandbox. According to git:
$git status
 # On branch master
$git pull
Already up-to-date.

https://github.com/Sylius/Sylius-Sandbox/blob/master/src/Sylius/Sandbox/Bundle/CoreBundle/Menu/Builder.php still shows $menu->setCurrentUri($this->container->get('request')->getRequestUri()); on line 160 and 198

**Comment by smuriu** [comment]
I also encounter the same problem on mine. It should be $menu->setCurrent(...) instead of $menu->setCurrentUri(...). This is only for the backend menus. The frontend menus are ok.

**Comment by Sergic** [comment]
have same error.
using latest version.
[Sun Aug 12 17:29:47 2012] [error] [client 192.168.255.1] PHP Fatal error:  Call to undefined method Knp\Menu\MenuItem::setCurrentUri() in /home/vhost/my/sandbox/sylius/src/Sylius/Sandbox/Bundle/CoreBundle/Menu/Builder.php on line 160, referer: http://sylius-sandbox.unreal.vm/dev.php/

**Comment by pjedrzejewski** [comment]
Should be fixed now. Sorry for the delay.

**Comment by grantlovell** [comment]
Seems to be working perfectly now. Thanks!
